version: "3.8"
services:
  web:
    build: .
    ports:
      - "8091:8090"
    networks:
      - backend
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "mvn", "exec:java", "-Dexec.mainClass=th.ac.ku.atm.AtmApplication"]
  db:
    image: mysql
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
networks:
  backend:
    driver: bridge
